rt:
  server: sysrt.directi.com
  port: 443
  user: biju.ch
  password: Abc@123
  ssl: true
  queues: [ 'automation', 'dotpw' ]
log:
  file: /dev/stdout
  level: DEBUG
last_sync: Wed Sep 21 15:00:00 2011
